#----------------------------------------------------------------
#
# Netronics CANdo Linux CANdoAUTOC make file
#
# Date - 15/09/14
#
#----------------------------------------------------------------
CFLAGS=-Wall
LFLAGS=-ldl -lm

CANdoC : CANdoAUTOC.c CANdoAUTOC.h CANdoImport.h
	gcc $(CFLAGS) CANdoAUTOC.c $(LFLAGS) -oCANdoAUTOC

#----------------------------------------------------------------
