#----------------------------------------------------------------
#
# Netronics CANdo Linux CANdoC make file
#
# Date - 15/09/14
#
#----------------------------------------------------------------
CFLAGS=-Wall
LFLAGS=-ldl

CANdoC : CANdoC.c CANdoC.h CANdoImport.h
	cc $(CFLAGS) CANdoC.c $(LFLAGS) -oCANdoC

#----------------------------------------------------------------
