#----------------------------------------------------------------
#
# Netronics CANdo Linux CANdo Detect make file
#
# Date - 15/09/14
#
#----------------------------------------------------------------
CFLAGS=-Wall
LFLAGS=-lusb-1.0

CANdoDetect : Main.c
	gcc $(CFLAGS) Main.c $(LFLAGS) -oCANdoDetect

#----------------------------------------------------------------
